### PR TITLE
tweak title and abstract to more clear talk about EDHOC.

### PR DESCRIPTION
**Pull request by mcr**
AFAIK, abstracts are not supposed to use acronyms, might need some more changes

### CODE REVIEW

**Comment by gselander** [comment]
I think we agreed in the meeting that we should have a setup that allows different instantiations and where BRSKI is one. Alternative formulation (inspired by this text) in #22

**Comment by mcr** [comment]
I'm looking forward to the description of what these other instantiations are.
Can you please give them names?  How do they differ?  How does mentioning that this is similar to BRSKI hurt?

**Comment by gselander** [comment]
> I'm looking forward to the description of what these other instantiations are.
Can you please give them names? 

We mentioned EAP and one-touch in the meeting.

> How do they differ? How does mentioning that this is similar to BRSKI hurt?

It does not. BRSKI is mentioned in #22, see Introduction.

**Comment by gselander** [comment]
Are people happy with doing #22 and closing this?

**Comment by malishav** [comment]
WFM

**Comment by gselander** [comment]
Closing this since #22 is merged.

**Pull request closed without merging**
